# Generated by Django 5.1.7 on 2025-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('league', 'League Admin'), ('club ', 'club Admin'), ('team', 'Team Admin'), ('user', 'Regular User')], default='user', max_length=20),
        ),
    ]
