# Generated by Django 5.1.7 on 2025-03-31 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('divison', models.CharField(choices=[('Top', 'Professional League'), ('second', 'Second League'), ('Third', 'Third League'), ('Amateur', 'Amaterur League')], default='Top', max_length=30)),
                ('gender', models.CharField(choices=[('unspecified', 'Unspecified'), ('M', 'Male'), ('F', 'Female')], default='unspecified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('unspecified', 'Unspecified'), ('M', 'Male'), ('F', 'Female')], default='unspecified', max_length=20)),
                ('referee_level', models.CharField(choices=[('fifa', 'Fifa'), ('national', 'National'), ('regional', 'Regional'), ('local', 'Local'), ('other', 'Other')], default='other', max_length=20)),
                ('current_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees_league', to='gamecore.league')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('current', models.BooleanField(default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues_season', to='gamecore.league')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('founded_year', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_clubs', to='gamecore.league')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_teams', to='gamecore.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('first', 'First Team'), ('second', 'second'), ('U21', 'Under 21'), ('U18', 'Under 18'), ('U16', 'Under 16'), ('Other', 'Other')], default='first', max_length=50)),
                ('gender', models.CharField(choices=[('unspecified', 'Unspecified'), ('M', 'Male'), ('F', 'Female')], default='unspecified', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_clubs', to='gamecore.club')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('unspecified', 'Unspecified'), ('M', 'Male'), ('F', 'Female')], default='unspecified', max_length=20)),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('nationality', models.CharField(max_length=100)),
                ('dominant_foot', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=10)),
                ('positions', models.CharField(choices=[('GK', 'GoalKeeper'), ('FB', 'Full Back'), ('CB', 'Central Defender'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('WB', 'Wing Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('WM', 'Winger'), ('ST', 'Striker'), ('WF', 'Winger Forward')], default='GK', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_team', to='gamecore.team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('unspecified', 'Unspecified'), ('M', 'Male'), ('F', 'Female')], default='unspecified', max_length=20)),
                ('age', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('nationality', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Acadamy', 'Acadamy Director'), ('head', 'Head Coach'), ('assistant', 'Assistant Coach'), ('First team', 'First team Coach'), ('Goalkeeping', 'Goalkeeping Coach'), ('Fitness', 'Fitness Coach'), ('Tactical', 'Tactical Coach'), ('Performace', 'Performace Analyst'), ('Youth', 'Youth Coach'), ('set-piece', 'Set-Piece Coach'), ('Rehabilitaion', 'Rehabilitaion Coach'), ('Scout', 'Scout')], default='head', max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_clubs', to='gamecore.club')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_teams', to='gamecore.team')),
            ],
        ),
    ]
