# Generated by Django 5.1.7 on 2025-03-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
