# Generated by Django 5.1.7 on 2025-04-02 10:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamecore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('round', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('home_team_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('away_team_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('compeleted', 'Compeleted'), ('postponed', 'Postponed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='gamecore.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='gamecore.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='gamecore.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='gamecore.season')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='gamecore.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(135)])),
                ('event_type', models.CharField(choices=[('default', 'Default'), ('goal', 'Goal'), ('assist', 'Assist'), ('yellow', 'Yellow Card'), ('red', 'Red card')], default='default', max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_assists', to='gamecore.player')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.fixtures')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='gamecore.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='gamecore.team')),
            ],
        ),
        migrations.CreateModel(
            name='Lineups',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='games.fixtures')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='gamecore.team')),
            ],
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('GK', 'GoalKeeper'), ('FB', 'Full Back'), ('CB', 'Central Defender'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('WB', 'Wing Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('WM', 'Winger'), ('ST', 'Striker'), ('WF', 'Winger Forward')], default='GK', max_length=10)),
                ('is_starter', models.BooleanField(default=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='gamecore.player')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='games.lineups')),
            ],
        ),
        migrations.CreateModel(
            name='MatchOfficals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('main', 'Main Referee'), ('assistant 1', 'Assistant Referee 1'), ('assistant 2', 'Assistant Referee 2'), ('fourth', 'Fourth Offical')], default='main', max_length=30)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_officals', to='games.fixtures')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gamecore.referee')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('possession', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_passes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shots_on_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shots_off_target', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fouls', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('corners', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('offsides', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='games.fixtures')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_stats', to='gamecore.team')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(135)])),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='games.fixtures')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_in', to='gamecore.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_out', to='gamecore.player')),
            ],
        ),
    ]
